apiVersion: capabilities.3scale.net/v1beta1
kind: Product
metadata:
  name: vllm-gpu-mistral
  namespace: 3scale
spec:
  name: "Mistral in vllm-gpu-mistral"
  systemName: "vllm-gpu-mistral"
  applicationPlans:
    standard:
      name: "Standard Plan"
      appsRequireApproval: false
      published: true
  methods:
    v1-models:
      friendlyName: List Models
      description: "List all models"
    v1-completions:
      friendlyName: Completions
      description: "Completions"
    v1-chat-completions:
      friendlyName: Chat Completions
      description: "Chat Completions"
  metrics:
    hits:
      description: Number of API hits
      friendlyName: Hits
      unit: hit
  mappingRules:
    - httpMethod: GET
      pattern: "/v1/models"
      increment: 1
      metricMethodRef: List Models
    - httpMethod: POST
      pattern: "/v1/completions"
      increment: 1
      metricMethodRef: Completions
    - httpMethod: POST
      pattern: "/v1/chat/completions"
      increment: 1
      metricMethodRef: Chat Completions
  policies:
    - configuration: {}
      configurationRef: {}
      enabled: true
      name: apicast
      version: builtin
    - configuration: {}
      configurationRef: {}
      enabled: true
      name: corsrequesthandling
      version: builtin
  backendUsages:
    vllm-gpu-mistral:
      path: /